In [4]:
import pandas as pd
import numpy as np

In [5]:
sales = pd.read_csv("Raw/sales.csv")
begin_inventory = pd.read_csv("Raw/begin_inventory.csv")
end_inventory = pd.read_csv("Raw/end_inventory.csv")
purchase_price = pd.read_csv("Raw/purchase_prices.csv")
purchases = pd.read_csv("Raw/purchases.csv")
vendor = pd.read_csv("Raw/vendor_invoice.csv")

# Handling Nulls

In [6]:
end_inventory.isnull().sum()

InventoryId       0
Store             0
City           1284
Brand             0
Description       0
Size              0
onHand            0
Price             0
endDate           0
dtype: int64

In [7]:
end_inventory["City"] = end_inventory["City"].fillna("Unknown")

In [8]:
end_inventory.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
endDate        0
dtype: int64

In [9]:
purchase_price.isnull().sum()

Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [10]:
purchase_price = purchase_price.dropna(subset=["Description"])

In [11]:
purchase_price.isnull().sum()

Brand             0
Description       0
Price             0
Size              0
Volume            0
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [12]:
purchases.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              3
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [13]:
vendor["Approval"] = vendor["Approval"].fillna("Pending")
vendor
vendor.isnull().sum()

VendorNumber    0
VendorName      0
InvoiceDate     0
PONumber        0
PODate          0
PayDate         0
Quantity        0
Dollars         0
Freight         0
Approval        0
dtype: int64

# Finding Duplicates

In [14]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [27]:
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12825358,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-17,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825359,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-21,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825360,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,3,77.97,25.99,2024-12-23,750.0,1,2.36,9165,ULTRA BEVERAGE COMPANY LLP
12825361,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-24,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825362,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,2,51.98,25.99,2024-12-29,750.0,1,1.57,9165,ULTRA BEVERAGE COMPANY LLP

In [15]:
dup = sales[sales.duplicated()]
print(dup)

Empty DataFrame
Columns: [InventoryId, Store, Brand, Description, Size, SalesQuantity, SalesDollars, SalesPrice, SalesDate, Volume, Classification, ExciseTax, VendorNo, VendorName]
Index: []

In [16]:
dup = begin_inventory[begin_inventory.duplicated()]
print(dup)

Empty DataFrame
Columns: [InventoryId, Store, City, Brand, Description, Size, onHand, Price, startDate]
Index: []

In [17]:
dup = end_inventory[end_inventory.duplicated()]
print(dup)

Empty DataFrame
Columns: [InventoryId, Store, City, Brand, Description, Size, onHand, Price, endDate]
Index: []

In [18]:
dup = purchases[purchases.duplicated()]
print(dup)

Empty DataFrame
Columns: [InventoryId, Store, Brand, Description, Size, VendorNumber, VendorName, PONumber, PODate, ReceivingDate, InvoiceDate, PayDate, PurchasePrice, Quantity, Dollars, Classification]
Index: []

In [19]:
dup = purchase_price[purchase_price.duplicated()]
print(dup)

Empty DataFrame
Columns: [Brand, Description, Price, Size, Volume, Classification, PurchasePrice, VendorNumber, VendorName]
Index: []

In [20]:
dup = vendor[vendor.duplicated()]
print(dup)

Empty DataFrame
Columns: [VendorNumber, VendorName, InvoiceDate, PONumber, PODate, PayDate, Quantity, Dollars, Freight, Approval]
Index: []

# Convert dates to actaul Dates

In [34]:
sales.info() # here we found salesdate column dtype is Object and we have to conver it to ACTUAL DATES

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       object
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      object
dtypes: float64(4), int64(5), object(5)
memory usage: 1.3+ GB

In [21]:
sales["SalesDate"] = pd.to_datetime(sales["SalesDate"])

In [22]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       datetime64[ns]
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      object
dtypes: datetime64[ns](1), float64(4), int64(5), object(4)
memory usage: 1.3+ GB

In [37]:
begin_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206529 entries, 0 to 206528
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  206529 non-null  object
 1   Store        206529 non-null  int64
 2   City         206529 non-null  object
 3   Brand        206529 non-null  int64
 4   Description  206529 non-null  object
 5   Size         206529 non-null  object
 6   onHand       206529 non-null  int64
 7   Price        206529 non-null  float64
 8   startDate    206529 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 14.2+ MB

In [23]:
begin_inventory["startDate"] = pd.to_datetime(begin_inventory["startDate"])

In [24]:
end_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224489 entries, 0 to 224488
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  224489 non-null  object
 1   Store        224489 non-null  int64
 2   City         224489 non-null  object
 3   Brand        224489 non-null  int64
 4   Description  224489 non-null  object
 5   Size         224489 non-null  object
 6   onHand       224489 non-null  int64
 7   Price        224489 non-null  float64
 8   endDate      224489 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 15.4+ MB

In [25]:
end_inventory["endDate"] = pd.to_datetime(end_inventory["endDate"])

In [26]:
purchase_price.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12260 entries, 0 to 12260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           12260 non-null  int64
 1   Description     12260 non-null  object
 2   Price           12260 non-null  float64
 3   Size            12260 non-null  object
 4   Volume          12260 non-null  object
 5   Classification  12260 non-null  int64
 6   PurchasePrice   12260 non-null  float64
 7   VendorNumber    12260 non-null  int64
 8   VendorName      12260 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 957.8+ KB

In [43]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   VendorNumber    int64
 6   VendorName      object
 7   PONumber        int64
 8   PODate          object
 9   ReceivingDate   object
 10  InvoiceDate     object
 11  PayDate         object
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: float64(2), int64(6), object(8)
memory usage: 289.6+ MB

In [27]:
purchases["ReceivingDate"] = pd.to_datetime(purchases["ReceivingDate"])
purchases["InvoiceDate"] = pd.to_datetime(purchases["InvoiceDate"])

In [28]:
vendor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   object
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   object
 5   PayDate       5543 non-null   object
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
 9   Approval      5543 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 433.2+ KB

In [32]:
vendor["InvoiceDate"] = pd.to_datetime(vendor["InvoiceDate"])
vendor["PODate"] = pd.to_datetime(vendor["PODate"])
vendor["PayDate"] = pd.to_datetime(vendor["PayDate"])

In [33]:
vendor

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,Pending
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,Pending
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,Pending
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,Pending
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,Pending
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,Pending
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,Pending
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,Pending
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,Pending
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,Pending

# Remove Extra Spaces and Case type

In [34]:
sales.columns = sales.columns.str.strip().str.title()
begin_inventory.columns = begin_inventory.columns.str.strip().str.title()
end_inventory.columns = end_inventory.columns.str.strip().str.title()
purchase_price.columns = purchase_price.columns.str.strip().str.title()
purchases.columns = purchases.columns.str.strip().str.title()
vendor.columns = vendor.columns.str.strip().str.title()

# Saving the cleaned dataset

In [38]:
#sales.to_csv("Sales_clean.csv")
begin_inventory.to_csv("begin_inventory_cleaned.csv",index=False,sep=",",encoding="utf-8")
end_inventory.to_csv("end_inventory_clened.csv",index=False,sep=",",encoding="utf-8")
purchase_price.to_csv("purchase_price_cleaned.csv",index=False,sep=",",encoding="utf-8")
purchases.to_csv("purchases_cleaned.csv",index=False,sep=",",encoding="utf-8")
vendor.to_csv("vendor_cleaned.csv",index=False,sep=",",encoding="utf-8")
sales.to_csv("sales_cleaned.csv",index=False,sep=",",encoding="utf-8")

In [48]:
sales.isnull().sum().sum()

0

In [1]:
import pandas as pd

test = pd.read_csv("begin_inventory_cleaned.csv")
print(test.head())

         Inventoryid  Store          City  Brand                  Description  \
0  1_HARDERSFIELD_58      1  HARDERSFIELD     58  Gekkeikan Black & Gold Sake
1  1_HARDERSFIELD_60      1  HARDERSFIELD     60       Canadian Club 1858 VAP
2  1_HARDERSFIELD_62      1  HARDERSFIELD     62     Herradura Silver Tequila
3  1_HARDERSFIELD_63      1  HARDERSFIELD     63   Herradura Reposado Tequila
4  1_HARDERSFIELD_72      1  HARDERSFIELD     72         No. 3 London Dry Gin

    Size  Onhand  Price   Startdate
0  750mL       8  12.99  2024-01-01
1  750mL       7  10.99  2024-01-01
2  750mL       6  36.99  2024-01-01
3  750mL       3  38.99  2024-01-01
4  750mL       6  34.99  2024-01-01

In [36]:
with open("begin_inventory_cleaned.csv", "r", encoding="utf-8") as f:
    print(repr(f.readline()))

'Inventoryid,Store,City,Brand,Description,Size,Onhand,Price,Startdate\n'

In [37]:
print(begin_inventory.shape)
print(begin_inventory.columns.tolist())

(206529, 9)
['Inventoryid', 'Store', 'City', 'Brand', 'Description', 'Size', 'Onhand', 'Price', 'Startdate']